=== ImMyst/kitto/.astro/collections/snippets.schema.json
{
  "$ref": "#/definitions/snippets",
  "definitions": {
    "snippets": {
      "type": "object",
      "properties": {
        "id": {
          "type": "number"
        },
        "title": {
          "type": "string"
        },
        "tags": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "libelle": {
                "type": "string"
              },
              "color": {
                "type": "string"
              }
            },
            "required": [
              "libelle",
              "color"
            ],
            "additionalProperties": false
          }
        },
        "code": {
          "type": "string"
        },
        "lang": {
          "type": "string",
          "enum": [
            "typescript",
            "javascript"
          ]
        },
        "$schema": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "title",
        "tags",
        "code",
        "lang"
      ],
      "additionalProperties": false
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== ImMyst/kitto/app/snippets/snippets.json
[
  {
    "id": 1,
    "title": "Test 1",
    "tags": [
      { "libelle": "Typescript", "color": "blue" },
      { "libelle": "Test", "color": "orange" }
    ],
    "code": "const lala = 'oui'; \nconst lala = 'oui';",
    "lang": "typescript"
  },
  {
    "id": 2,
    "title": "Test 2",
    "tags": [
      { "libelle": "Javascript", "color": "green" },
      { "libelle": "Test", "color": "blue" }
    ],
    "code": "const filteredAdditionalColumns = currentVue?.id === VUE_JOURNAL_SALAIRE_FULL\n ? additionalColumns.filter((col) => col?.name !== 'lbu_taux_sal' && col?.name !== 'lbu_taux_pat')\n : additionalColumns;",
    "lang": "javascript"
  }
]
